### PR TITLE
removed kms access for proxy

### PR DESCRIPTION
**Pull request by samsanders23**
Removing access to KMS for Proxy. Proxy is still able to connect without any errors. From this I assume that Proxy does not require explicit KMS permissions to secrets manager if it is using the default CMK.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rezabekf** [comment]
Assuming, you have tested this and KMS is not needed to decrypt the key (this may be due to a default encryption key used and KMS is only required for CMK). Could you please verify if Proxy is in state `Active` when KMS key is removed?

**Comment by samsanders23** [comment]
Proxy remains fully functional in the active state when these permissions are removed.

**Review by rezabekf — APPROVED** [review]
LGMT

**Comment by rezabekf** [comment]
You can merge this PR

**Pull request merged**
